UnminedCustomMarkers = {

    isEnabled: true,

    markers: [
        {
            x: 438,
            z: 313,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "猪灵交易",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: -134,
            z: -19,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "烈焰人农场",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 176,
            z: 248,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "十六联刷铁机",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: -1301,
            z: 536,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "主世界伪和平",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: -580,
            z: 780,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "疣猪兽农场",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 64,
            z: 199,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "不祥之兆药水塔",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 136,
            z: 343,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "猪人塔",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 750,
            z: 420,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "史莱姆农场",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 176,
            z: 248,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "100倍速熔炉组",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 1405,
            z: 1857,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "下界伪和平",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: -572,
            z: 615,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "渔场",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: -200,
            z: 211,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "溺尸塔",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 494,
            z: 379,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "80w猪人塔",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 839,
            z: 818,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "猪人塔",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },

    ]
}
