UnminedCustomMarkers = {

    isEnabled: true,

    markers: [

        {
            x: 1467,
            z: 1961,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "十六联刷铁机",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 147,
            z: -593,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "骨粉机",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 6170,
            z: 3363,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "女巫塔",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 226,
            z: -5299,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "8*刷沙机",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 1600,
            z: 1928,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "黑曜石机",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: -6040,
            z: 4794,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "沼泽刷怪塔",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 151,
            z: -543,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "128熔炉组",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: -4727,
            z: 5002,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "袭击塔",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 574,
            z: -434,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "竹子机",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: -1050,
            z: -453,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "刷冰机",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
    ]
}
