UnminedCustomMarkers = {

    isEnabled: true,

    markers: [

        {
            x: -436,
            z: 0,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "村民交易所",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: -112,
            z: -422,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "合成站",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: -150,
            z: -460,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "树场",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 95,
            z: -50,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "40核蜂蜜机",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 585,
            z: 790,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "凋灵玫瑰农场",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: 5,
            z: 237,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "小黑塔",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
        {
            x: -123,
            z: -475,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "刷石机",
            textColor: "purple",
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Arial",
        },
    ]
}
